import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "keen-slider/keen-slider.min.css";
import "./globals.css";
import Head from 'next/head';
import Navbar from "./Components/Navbar";
import MobNav from "./Components/MobNav";
import TopNav from "./Components/TopNav";
import Footer from "./Components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400,700&display=swap"
        />
      </Head>
      <body className={inter.className}>
        <TopNav />
        <Navbar />
        <div className="lg:hidden">
          <MobNav />
        </div>
        
        {children}
        <Footer />
        </body>

    </html>
  );
}
